Refactored some components and removed color themes
gudzilla/react-todoApp pull request #1
Opened 2024-05-23 17:00 UTC by gudzilla

Refactored some components and removed color themes

2024-05-29 08:07 UTC, Muslik requested changes

2024-05-29 08:07 UTC, Muslik commented on src/components/todoApp/TodoApp.jsx
> +  let renderList = todoList.filter(FILTERS[todoListFilter]);
Тут будет константа например `FILTER_PREDICATE[todoListFilter]`

2024-05-29 08:07 UTC, Muslik commented on src/components/todoApp/TodoApp.jsx
>    const isListCompleted = todoList.every((item) => item.isDone);
Тут можно использовать готовую функцию из константы

2024-05-29 08:07 UTC, Muslik commented on src/components/todoApp/TodoApp.jsx
>      const newList = todoList.map((item) => {
Ниже, после первого `return` не нужен `else`

2024-05-29 08:07 UTC, Muslik commented on src/components/todoApp/TodoApp.jsx
>            onAllDoneOrUndone={handleCheckAllOrUncheckAll}
Передаешь ненужные пропсы

2024-05-29 08:07 UTC, Muslik commented on src/components/todoList/TodoList.jsx
>  import { useState, useRef, useEffect } from "react";
useRef - не нужен

2024-05-30 07:22 UTC, gudzilla commented on src/components/todoFilters/TodoFilters.jsx
> +          setFilter("all");
![filters](https://github.com/gudzilla/react-todoApp/assets/57419893/1b82feb6-5bd1-4993-9fbb-9597ed77e7be)
![setFilters](https://github.com/gudzilla/react-todoApp/assets/57419893/70ec321e-5bb8-45b4-8723-4e810dbed491)
Окей, у фильтров будут свой id со строкой и функция для сортировки.

2024-05-30 07:25 UTC, gudzilla commented on src/constants/filters.js
> +  all: filterAll,
Решение предыдущего замечания решает эту проблему

2024-05-30 07:26 UTC, gudzilla commented on src/components/todoApp/TodoApp.jsx
> +  let renderList = todoList.filter(FILTERS[todoListFilter]);
Теперь у меня `renderList` фильтруется следующим образом:

2024-05-30 07:31 UTC, gudzilla commented on src/components/todoApp/TodoApp.jsx
>    const isListCompleted = todoList.every((item) => item.isDone);
`todoList.every((item) => item.isDone);` вот это вынести в отдельную функцию?

2024-05-30 07:44 UTC, gudzilla commented on src/components/todoApp/TodoApp.jsx
>      const newList = todoList.map((item) => {
Разве с `else` не проще читается ?

2024-05-31 06:00 UTC, gudzilla commented on src/components/todoApp/TodoApp.jsx
> +  let renderList = todoList.filter(FILTERS[todoListFilter]);
Понял, сделал

2024-07-04 08:55 UTC, gudzilla commented on src/components/itemEditMode/ItemEditMode.jsx
>    useEffect(() => {
Изменил

2024-07-04 12:15 UTC, gudzilla commented on src/components/todoApp/TodoApp.jsx
>      const newList = todoList.map((item) => {
`else` убрал

2024-07-06 09:49 UTC, Muslik approved these changes

2024-07-06 10:52 UTC, merged